name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - requests
  - igv-reports==1.8.0
  - samtools==1.9
  - bowtie2
  - bioconda::salmon==0.9.1
  - bioconda::picard
  - bioconda::htseq
  - bioconda::multiqc
  - bioconda::perl-io-gzip
  - bioconda::perl-set-intervaltree
  - bioconda::perl-db-file
  - bioconda::perl-uri
  - bioconda::perl-carp
  - bioconda::perl-json
  - numpy
  - star
  - pip
