name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - openjdk
  - samtools
  - bowtie2
  - bioconda::picard
  - bioconda::salmon
  - numpy
  - star=2.7.10a
  - arriba=2.3.0
  - bioconda::igv-reports=1.8.0
  - requests
  - pip
  
  

